version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - '3306:3306'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'